/* APPLICATION ACTIONS */
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const HIDE_MENU = 'HIDE_MENU';
export const SHOW_MENU = 'SHOW_MENU';

/* FEED ACTIONS */
export const FETCH_FEED = 'FETCH_FEED';
export const SUCCESSFUL_FEED_FETCH = 'SUCCESSFUL_FEED_FETCH';
export const FAILED_FEED_FETCH = 'FAILED_FEED_FETCH';

/* SERIES ACTIONS */
export const FETCH_SERIES = 'FETCH_SERIES';
export const SUCCESSFUL_SERIES_FETCH = 'SUCCESSFUL_SERIES_FETCH';
export const FAILED_SERIES_FETCH = 'FAILED_SERIES_FETCH';

/* SEASON ACTIONS */
export const FETCH_SEASON = 'FETCH_SEASON';
export const SUCCESSFUL_SEASON_FETCH = 'SUCCESSFUL_SEASON_FETCH';
export const FAILED_SEASON_FETCH = 'FAILED_SEASON_FETCH';
